services:
  - type: web
    name: event-management-system
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Dserver.port=8080
    healthCheckPath: /health
    autoDeploy: true