services:
  - type: web
    name: event-management-system
    env: docker
    plan: free
    startCommand: "java -jar target/EventManagementSystem.war"

  - type: pserv
    name: event-ms-db
    plan: free
    database: event_ms_db