services:
  - type: web
    name: event-management-system
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Dserver.port=8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_SECURITY_USERNAME
        value: admin
      - key: SPRING_SECURITY_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true