services:
  - type: web
    name: event-management-system  # This is the name you'll use as your Blueprint Name
    env: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/EventManagementSystem.war"
    envVars:
      - key: PORT
        value: 8080
      - key: MYSQL_HOST
        fromService:
          type: mysql
          name: event-ms-db
          property: host
      - key: MYSQL_PORT
        fromService:
          type: mysql
          name: event-ms-db
          property: port
      - key: MYSQL_DATABASE
        fromService:
          type: mysql
          name: event-ms-db
          property: database
      - key: MYSQL_USER
        fromService:
          type: mysql
          name: event-ms-db
          property: username
      - key: MYSQL_PASSWORD
        fromService:
          type: mysql
          name: event-ms-db
          property: password
    dependsOn:
      - event-ms-db

  - type: mysql
    name: event-ms-db
    plan: free
    ipAllowList: []  # Allow all IPs
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1