CREATE TABLE IF NOT EXISTS events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    location VARCHAR(255) NOT NULL,
    description CLOB,
    guest_limit INTEGER NOT NULL CHECK (guest_limit > 0),
    current_guests INTEGER DEFAULT 0 CHECK (current_guests >= 0),
    event_type VARCHAR(20) NOT NULL DEFAULT 'SIMPLE',
    parent_event_id INTEGER REFERENCES events(event_id) ON DELETE CASCADE,
    image_path VARCHAR(500),
    CHECK (current_guests <= guest_limit)
);;

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INTEGER NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    user_name VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    digital_id VARCHAR(255) NOT NULL,
    booking_type VARCHAR(20) NOT NULL DEFAULT 'SUB_EVENT',
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_email, event_id)
);;

CREATE TABLE IF NOT EXISTS app_users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
